require('dotenv').config();
const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),admin=require('firebase-admin');
const Service=require('./models/Service'),User=require('./models/User');
const app=express();app.disable('x-powered-by');app.use(cors({origin:process.env.CORS_ORIGIN||'*'}));app.use(express.json({limit:'1mb'}));
function initFirebase(){try{if(!process.env.FIREBASE_SERVICE_ACCOUNT)return null;if(admin.apps.length)return admin.app();return admin.initializeApp({credential:admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT))})}catch(e){console.error('Firebase init failed:',e.message);return null}}
app.get('/',(q,s)=>s.json({name:'Amroha One API',version:'2.0.1',status:'ok'}));
app.get('/health',(q,s)=>s.json({status:'ok',appName:'Amroha One',database:mongoose.connection.readyState===1?'connected':'disconnected',fcm:Boolean(app.locals.firebaseAdmin),services:{tiffin:true,porter:false,cityServices:false,grocery:false}}));
// Mobile clients use HTTPS + JWT for protected operations. No secret API key is embedded in the APK.
app.use('/api/vendors',require('./routes/vendors'));app.use('/api/auth',require('./routes/auth'));app.use('/api/profile',require('./routes/profile'));app.use('/api/services',require('./routes/services'));app.use('/api/products',require('./routes/products'));app.use('/api/orders',require('./routes/orders'));app.use('/api/tracking',require('./routes/tracking'));app.use('/api/admin',require('./routes/admin'));app.use('/api/delivery',require('./routes/delivery'));
app.use((e,q,s,n)=>{console.error(e);if(e.code===11000)return s.status(409).json({error:'Duplicate record'});if(e.name==='ValidationError')return s.status(400).json({error:e.message});s.status(500).json({error:'Internal server error'})});
async function start(){if(!process.env.MONGODB_URI||!process.env.JWT_SECRET)throw new Error('MONGODB_URI and JWT_SECRET are required');await mongoose.connect(process.env.MONGODB_URI,{serverSelectionTimeoutMS:10000});const defs=[['TIFFIN','Amroha Tiffin',true,1],['PORTER','Amroha Porter',false,2],['CITY_SERVICES','Amroha City Services',false,3],['GROCERY','Amroha Grocery',false,4]];for(const [key,name,active,sortOrder] of defs)await Service.updateOne({key},{$setOnInsert:{key,name,active,sortOrder,description:name+' service'}},{upsert:true});if(process.env.ADMIN_PHONE&&process.env.ADMIN_PASSWORD&&!await User.exists({phone:process.env.ADMIN_PHONE})){const u=await User.create({name:process.env.ADMIN_NAME||'Amroha One Admin',phone:process.env.ADMIN_PHONE,email:'',passwordHash:await bcrypt.hash(process.env.ADMIN_PASSWORD,12),role:'ADMIN'});console.log('Admin seeded:',u.phone)}app.locals.firebaseAdmin=initFirebase();const port=Number(process.env.PORT||10000);app.listen(port,'0.0.0.0',()=>console.log('Amroha One API 2.0.1 listening on '+port))}start().catch(e=>{console.error('Startup failed:',e.message);process.exit(1)});
